/* ユーザーマスタ作成 */
CREATE TABLE USERINFO (
  ID         CHAR(9)  NOT NULL,
  PASS       VARCHAR(64)  NOT NULL,
  CODE       CHAR(8)  NOT NULL,
  NAME       VARCHAR(50) NOT NULL,
  PAID       INT DEFAULT '20' NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT fk_code FOREIGN KEY (CODE) REFERENCES DEPARTMENT(CODE)
);

CREATE TABLE DEPARTMENT (
  CODE       CHAR(8)  NOT NULL,
  CODENAME   CHAR(50) NOT NULL,
  PRIMARY KEY(CODE)
);
